#!/bin/sh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
[ $(pamixer --get-mute) = true ] && exit 0
pamixer --allow-boost -d 5
