#!/bin/sh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
[ $(pamixer --get-mute) = true ] && exit 0
vol="$(pamixer --get-volume)"
[ "$vol" -le "95" ] && pamixer --allow-boost -i 5
