#!/bin/sh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
bluetoothStatus="$(systemctl status bluetooth | rg 'Active: active \(running\)')"
if [[ -z "$bluetoothStatus" ]]; then
   systemctl start bluetooth && blueman-applet && exit 0
else
   systemctl stop bluetooth && killall blueman-applet && exit 0
fi
