#!/bin/sh -x
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################

status=$(pgrep -f 'nerd-dictation begin')

if [[ "$status" ]]; then
    nerd-dictation end && notify-send --hint=string:x-dunst-stack-tag:test 'Dictation' "STOPPED" && exit 0;
else
    nerd-dictation begin --vosk-model-dir=$HOME/.local/share/nerd-dictation/model&
    [ "$(pgrep -f 'nerd-dictation begin')" ] && notify-send --hint=string:x-dunst-stack-tag:test 'Dictation' "STARTED"
fi
