#!/bin/bash
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
monitor_1080p="$(xrandr 2>/dev/null | grep ' connected (' | cut -d' ' -f1)"
monitor_2k="$(xrandr 2>/dev/null | grep ' connected 2560x1440+0+0 ' | cut -d' ' -f1)"
if [[ ! -z "$monitor_2k" ]] && [[ ! -z "$monitor_1080p" ]]; then
    xrandr --output "$monitor_2k" --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output "$monitor_1080p" --mode 1920x1080 --pos 0x180 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output HDMI-0 --off --output DP-4 --off --output DP-5 --off
elif [[ -z "$monitor_2k" ]] && [[ ! -z "$monitor_1080p" ]]; then
    xrandr --output "$monitor_1080p" --primary --mode 1920x1080 --rotate normal --output "$monitor_2k" --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output HDMI-0 --off --output DP-4 --off --output DP-5 --off
else
    xrandr --output "$monitor_2k" --primary --mode 2560x1440 --rotate normal --output "$monitor_1080p" --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output HDMI-0 --off --output DP-4 --off --output DP-5 --off
fi

xwallpaper --zoom $HOME/.config/xwallpaper/wallpaper
