#!/bin/sh -x
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
git log --pretty='format:%Cgreen%h %Creset%cd %Cblue[%cn] %Creset%s%C(yellow)%d%C(reset)' --graph --date=relative --decorate --all |\
fzf -m |\
rg -NoP '[\|\s]*[\*]\s*[\|\s]*[\|/\s]*[\|\\]*[\\]*[\s]*\K\w{7}' |\
xargs -I {} git diff {}^ {}
