#!/bin/sh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
filename="$(basename $(pwd))"
[[ ! -z "$1" ]] && filename="$1"
cp $SYNCDRIVE/Templates/Latex/Makefile ./ && echo "Copied $SYNCDRIVE/Templates/Latex/Makefile"
cp $SYNCDRIVE/Templates/Latex/new.tex "./$filename.tex" && echo "Copied $SYNCDRIVE/Templates/Latex/new.tex -> $filename.tex"
sed -i -E "1 s/(filename=)/\1$filename/" ./Makefile
