#!/bin/sh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
quarter_dir="$SYNCDRIVE/2021-22Q3Spring"
file_name="$(date '+%Y-%m-%d').md"
class_header=""
class="$1"
topic="$2"


while getopts ":n:" option; do
   case $option in
   n) file_name="$OPTARG.md"
       class="$3"
       topic="$4";;
   esac
done

[[ -z "$class" ]] && class="$(basename "$(pwd)")"

case "$class" in
    c467|cs467|CSCD467-ParallelCloudComputing)
        class_header="\nCSCD467 Parallel & Cloud Computing<br>"
        cd "$quarter_dir/CSCD467-ParallelCloudComputing"
    ;;
    c490|cs490|CSCD490-SeniorCapstone)
        class_header="\nCSCD490 Senior Capstone<br>"
        cd "$quarter_dir/CSCD490-SeniorCapstone"
    ;;
    c202|cs202|CSCD202-ComputingEthics)
        class_header="\nCSCD202 Computing Ethics<br>"
        cd "$quarter_dir/CSCD202-ComputingEthics"
    ;;
    *) topic="$class";;
esac

[[ ! -d 'Notes' ]] && mkdir Notes

cd Notes

[[ ! -f "$file_name" ]] && printf "Created: $(date '+%a %b %d, %Y %H:%M')\n\nUpdated: \n$class_header\n## $topic\n" > "$file_name" || sed -i "s#Updated:.*#Updated: $(date '+%a %b %d, %Y %H:%M')#" "$file_name"

$EDITOR "$file_name" || open "$file_name" || xdg-open "$file_name"
