#!/bin/sh
#############################################################
# @author Mia Hunt
#############################################################
export LD_PRELOAD=/usr/lib/spotifywm.so
/opt/spotify/spotify "$@"
