#!/usr/bin/zsh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
feh_pid=$(pgrep -f 'feh https://i.scdn.co/image/*')
if [[ ! -z $feh_pid ]]; then
    kill -9 $feh_pid
else
    sp feh
fi
