#!/bin/sh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
# Autostart settings
$HOME/.config/.system/settings.sh
$HOME/.config/.system/dwm-bar.sh
# dwmblocks
exec dwm
