#!/bin/sh
spotifyStatus="$(playerctl --player=spotify,spotifyd status)"
mpvStatus="$(playerctl --player=mpv status)"
status="$(playerctl status)"
if [[ "$spotifyStatus" = 'Playing' ]]; then
    playerctl --player=spotify metadata --format "{{title}}\n{{artist}}\n{{album}}"
elif [[ "$mpvStatus" = 'Playing' ]]; then
    playerctl --player=mpv metadata --format "{{title}}\n{{artist}}\n{{album}}"
elif [[ "$status" = 'Playing' ]]; then
    playerctl metadata --format "{{title}}\n{{artist}}\n{{album}}"
elif [[ "$spotifyStatus" = 'Paused' ]]; then
    playerctl --player=spotify metadata --format "{{title}}\n{{artist}}\n{{album}}"
elif [[ "$mpvStatus" = 'Paused' ]]; then
    playerctl --player=mpv metadata --format "{{title}}\n{{artist}}\n{{album}}"
elif [[ "$status" = 'Paused' ]]; then
    playerctl metadata --format "{{title}}\n{{artist}}\n{{album}}"
else
    echo "no players"
    exit 1
fi
