#!/bin/sh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
[ $(pamixer --get-mute) = true ] && notify-send --hint=string:x-dunst-stack-tag:test "Volume Muted" && exit

vol="$(pamixer --get-volume)"
notify-send --hint=string:x-dunst-stack-tag:test "$(pamixer --get-default-sink | sed 1d | cut -d'"' -f 4)" "Volume $vol%"
