#!/bin/sh
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################
[ $(pamixer --get-mute) = true ] && notify-send --hint=string:x-dunst-stack-tag:test "$(pamixer --get-default-sink | sed 1d | cut -d'"' -f 4)" "Volume Muted" && exit 0
pamixer --allow-boost -d 5
notify-send --hint=string:x-dunst-stack-tag:test "$(pamixer --get-default-sink | sed 1d | cut -d'"' -f 4)" "Volume $(pamixer --get-volume)%"
