USE worldC2 AS REFERENCE 31*47'18.384"/139*56'41.6034";

CREATE TRACK END end1 REFERENCE $worldC2 DELTA START 400:0 END -400:0;
CREATE TRACK LAYOUT line_track WITH TRACKS end1;

CREATE STOCK ENGINE left_engine AS DIESEL ON TRACK end1 DISTANCE 0 FROM END FACING START;
CREATE STOCK ENGINE right_engine AS DIESEL ON TRACK end1 DISTANCE 0 FROM START FACING START;

COMMIT;
OPEN VIEW viewC2 ORIGIN $worldC2 WORLD WIDTH 1000 SCREEN WIDTH 800 HEIGHT 600;

DO SET REFERENCE ENGINE left_engine;
DO SET left_engine SPEED 100;
DO SET REFERENCE ENGINE right_engine;
DO SET right_engine SPEED 100;
