#!/bin/sh 
#############################################################
# @author Mia Hunt
# @github kaykay38
#############################################################

status=$(pgrep -f 'nerd-dictation begin')

[[ "$status" ]] && printf "  " || printf ""
