#!/bin/sh

# Show wifi 直 and percent strength or 睊 if none.
# Show  if connected to ethernet or ✗ if none.
# Show 🔒 if a vpn connection is active

#case $BLOCK_BUTTON in
#	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
#	3) notify-send "🌐 Internet module" "\- Click to connect
#睊: no wifi connection
#直: wifi connection with quality
#: no ethernet
#: ethernet working
#ﱾ: vpn is active
#" ;;
#	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
#esac

printf "%s%s%s\n" "$(sed "s/.*/  ﱾ /" /sys/class/net/tun*/operstate 2>/dev/null)" "$(sed "s/up/  直 /;s/down/  睊 /" /sys/class/net/w*/operstate 2>/dev/null)" "$(sed "s/down//;s/up/    /" /sys/class/net/enp4s0/operstate 2>/dev/null)"
